version: "3"

services:
  # single-threaded-tests-db:
  #   container_name: single-threaded-tests-db
  #   image: postgres:16
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: pass
  #     POSTGRES_DB: test

  # multi-threaded-tests-db:
  #   container_name: multi-threaded-tests-db
  #   image: postgres:16
  #   ports:
  #     - "5433:5433"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: pass
  #     POSTGRES_DB: test

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      # POSTGRES_DB: test
